# Generated by Django 4.1.6 on 2023-05-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='main.body')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('hr', 'horizontally'), ('ver', 'vertically')], default='hr', max_length=3, verbose_name='Положение на фото')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.body')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.floor')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Hallway',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.section')),
                ('x', models.CharField(max_length=20, verbose_name='X')),
                ('y', models.CharField(max_length=20, verbose_name='Y')),
                ('w', models.CharField(max_length=20, verbose_name='W')),
                ('h', models.CharField(max_length=20, verbose_name='H')),
                ('x_end', models.CharField(max_length=20, verbose_name='X_end')),
                ('y_end', models.CharField(max_length=20, verbose_name='Y_end')),
                ('height', models.CharField(max_length=20, verbose_name='height')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('x', models.CharField(max_length=20, verbose_name='X')),
                ('y', models.CharField(max_length=20, verbose_name='Y')),
                ('w', models.CharField(max_length=20, verbose_name='W')),
                ('h', models.CharField(max_length=20, verbose_name='H')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='main.section')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor_id', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='main.section')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
